### ISSUE TITLE
How to listen for text changes in 'fabric.Textbox'?

### ISSUE THREAD

**Issue by glk-hll** [guesant/fabricjs-object-fit#14]

**Comment by guesant** [comment]
http://stackoverflow.com/questions/26998724/ddg#26998807

Answer made by [xenyal](https://stackoverflow.com/users/3157745/xenyal):

> ```ts
> object.on('changed', function(e) {
>    console.log('changed', object, e);
> });
> ```
> ```ts
> canvas.on('text:changed', function(e) {
>    console.log('text:changed', e.target, e);
> });
> ```

**Comment by glk-hll** [comment]
Ok, Thank you very much.
