### ISSUE TITLE
`objectFit.set({ stroke: '...' })` to have a bug?

### ISSUE THREAD

**Issue by glk-hll** [guesant/fabricjs-object-fit#18]
```js
container.set({
   stroke: 'red',
   strokeWidth: 40
})
```
effect:
![{3DFFB168-8D89-E907-F0D6-6D80B65E052E}](https://user-images.githubusercontent.com/44257305/153829995-69716c11-057d-4ba5-8611-9e6cf475f8d8.jpg)
@guesant

**Comment by guesant** [comment]
Hello, thanks for reporting. I'll take a look.

**Comment by guesant** [comment]
@glk-hll 

After investigating a bit, I found that:

- Setting "stroke" and "strokeWidth" in `fabric.Group`s has no effect.

- ObjectFit uses fabric.Group under the hood.

- It is still possible to draw borders, see [this comment](https://github.com/guesant/fabricjs-object-fit/issues/17#issuecomment-1047920853) and [this demo](https://jsfiddle.net/2bxna3gk/3/).

**Comment by glk-hll** [comment]
However, when playing video in canvas,  ` canvas Renderall() ` the above code will be invalid. [playing video example](http://fabricjs.com/video-element).
```js
render() {
   canvas.renderAll()
   fabric.util.requestAnimFrame(render.bind(this))
}
```

**Comment by guesant** [comment]
@glk-hll try [this](https://jsfiddle.net/mxezf2vr/1/).

**Comment by glk-hll** [comment]
ok, thanks.

**Comment by glk-hll** [comment]
@guesant The content of this link can no longer be viewed,[this](https://jsfiddle.net/mxezf2vr/1/).
