### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by ibrahimrehman1** [guesant/fabricjs-object-fit#21]
I am using this package to achieve object-fit: cover functionality and its working perfectly fine. But I realized that now my filters are not working. It says 

```
applyFilters() is not a function

```

Kindly look into it. Thanks!

**Comment by ibrahimrehman1** [comment]
Ok, so I found the fix for this. Instead of directly calling applyFilters(), just so something like this:

```
someObject._object.applyFilters()

```
Here _object refers to the image which we have added into the container.

**Comment by guesant** [comment]
Hello @ibrahimrehman1. Thanks for reporting. 
I'll take a look and maybe create a RFC for a better API or documentation.
