### ISSUE TITLE
Can the 'container' created with 'fabricjs object fit' be filled with solid colors and switched between filling solid colors or pictures? Like 'figma'?

### ISSUE THREAD

**Issue by glk-hll** [guesant/fabricjs-object-fit#6]

**Comment by guesant** [comment]
What do you mean by "figma"?

---

Your first question:

> How to dynamically modify the 'mode' of the 'container' created with 'fabricjs object fit' [...]

```ts
//
container.mode = "none";
container.recompute();
canvas.requestRenderAll();
//
container.mode = "scale-down";
container.recompute();
canvas.requestRenderAll();
```

---

> Can the 'container' created with 'fabricjs object fit' be filled with solid colors and switched between filling solid colors or pictures? Like 'figma'?

Of course! I made an example on [jsFiddle](https://jsfiddle.net/4y5nr1k6/), but here is the code:

```ts
const {
  setup
} = window.FabricJSObjectFit;

const {
  ObjectFit
} = setup(fabric);

const getRandInt = (min, max) => min + Math.floor(Math.random() * (max - min));

const getRandomByte = () => getRandInt(0, 255);

const getRandomRGBColor = () => `rgb( ${getRandomByte()}, ${getRandomByte()}, ${getRandomByte()} )`;

const getRandomRect = () => new fabric.Rect({
  width: getRandInt(30, 90),
  height: getRandInt(30, 90),
  fill: getRandomRGBColor()
});

const getRandomImage = () => new Promise(resolve => fabric.Image.fromURL(`https://via.placeholder.com/${getRandInt(100, 200)}x${getRandInt(100, 200)}`, resolve));

const getRandomObject = () => {
  // we dont want that our IP got blocked from placeholder.com ;P
  if (Math.random() > 0.75) {
    return getRandomImage();
  }
  return getRandomRect();
}


async function render() {
  const canvas = new fabric.Canvas("c");

  const container = new ObjectFit(await getRandomObject(), {
    width: 200,
    height: 150,
    mode: "contain"
  });

  // container at the canvas center
  container.set({
    originX: "center",
    originY: "center",
    left: canvas.width / 2,
    top: canvas.height / 2,
  });

  container.setCoords();

  canvas.add(container);

  canvas.renderAll();

  // each 1s it changes randomly the object
  setInterval(async () => {
    container.setObject(await getRandomObject());
    container.recompute();
    canvas.requestRenderAll();
  }, 1000);
}

render();
```

**Comment by glk-hll** [comment]
@guesant 
1. `figma`  -> https://www.figma.com , I'm doing something like it.
2. After using "setobject" to change to another picture, the width and height of "objectfit" are both 0. Why?

**Comment by guesant** [comment]
> 1. `figma`  -> https://www.figma.com , I'm doing something like it.
> 2. After using "setobject" to change to another picture, the width and height of "objectfit" are both 0. Why?

1. ok

2. That's not supposed to happen. @glk-hll could you provide a reproducible script of your bug? Maybe it's related to #9

**Comment by guesant** [comment]
@glk-hll 
> 2. After using "setobject" [...]

I don't know if it's a typo, but in "setObject" the letter "O" is capitalized.

**Comment by glk-hll** [comment]
@guesant Thanks! I solved the previous problem in another way. The problem is not the case of 'setobject()';
Now I have a new problem:
```js
 const instance = new ObjectFit(img)
 instance.set('customProps', {
    id: 1
 })
 
 canvas.toJSON(['customProps']) // How to make 'objectfit' in 'canvas Can I bring the custom attribute 'customprops' when tojson (['customprops'])?
```

**Comment by guesant** [comment]
@glk-hll 

Oops! I had forgotten to implement "propertiesToInclude" in ObjectFit#toObject. I published a fix in version "0.0.0-beta.4".

Could you update the library and test if this bug keeps happening in the latest version (0.0.0-beta.5)?

Cheers.

**Comment by glk-hll** [comment]
@guesant OK Cheers.

**Comment by glk-hll** [comment]
@guesant After I updated to the new version, this problem has been solved. Thank you. I'm testing the previous question about 'setobject()'. well done.

**Comment by guesant** [comment]
@glk-hll I will close this issue for now. Feel free to reopen or create a new one.
